version: '3.1'

services:

  app:
    build: .
    links:
      - nodejs
      - database
      - redis

  nodejs:
    image: node:8.7.0
    ports:
      - "8080:80"

  database:
    image: postgres:10.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123

  redis:
    image: redis:3.2.11
    ports:
      - "6379:6379"