version: '3.1'

services:

  app:
    build: .
    links:
      - nodejs
      - postgres
      - redis

  nodejs:
    image: node:8.7.0
    ports:
      - "8080:5000"
    volumes:
      - .:/docker-mount
    working_dir: /docker-mount
    entrypoint: ./entrypoint.sh

  postgres:
    image: mdillon/postgis:9.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./sql/atlas_of_thrones.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:3.2.11
    ports:
      - "6379:6379"